### PR TITLE
Add go mod file

### PR DESCRIPTION
**Pull request by chughes-pika**
I recently came across your project and it has helped me out quite a bit.  Internally though, we use go modules for package management and I was hoping you might add `go.mod` to your project and tag your project head `v1.0.0`.

### Tested
Ran `go test./...` locally

### CODE REVIEW

**Comment by nathan-osman** [comment]
Thanks for the pull request! I'd love to add support for Go modules to the package.

**Comment by nathan-osman** [comment]
I'll set a reminder to tag the release when I get home later. 🙂

**Comment by chughes-pika** [comment]
@nathan-osman Reminder to tag the head commit

**Comment by nathan-osman** [comment]
> @nathan-osman Reminder to tag the head commit

D'oh, sorry about that. Done. 👍

**Pull request merged**
